definitions:
  internal.Task:
    properties:
      id:
        type: integer
      name:
        type: string
      time_begin:
        type: string
      time_end:
        type: string
      user_id:
        type: integer
    type: object
  internal.User:
    properties:
      address:
        type: string
      id:
        type: integer
      name:
        type: string
      passportNumber:
        type: string
      patronymic:
        type: string
      surname:
        type: string
    type: object
host: localhost:9090
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /create_user:
    post:
      consumes:
      - application/json
      parameters:
      - description: Passport data
        example: '{"passportNumber": "1111 123456"}'
        in: path
        name: passportNumber
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
        "400":
          description: Invalid input
        "408":
          description: Request timeout
        "500":
          description: Internal server error
      summary: Create user
      tags:
      - users
  /delete_user:
    delete:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: body
        name: id
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
        "400":
          description: Invalid input
        "408":
          description: Request timeout
        "500":
          description: Internal server error
      summary: Delete user
      tags:
      - users
  /get_user_info:
    post:
      consumes:
      - application/json
      parameters:
      - description: Page number
        in: query
        name: page
        required: true
        type: string
      - description: Number of items per page
        in: query
        name: per_page
        required: true
        type: string
      - description: User details
        in: body
        name: user
        schema:
          $ref: '#/definitions/internal.User'
      produces:
      - application/json
      responses:
        "200":
          description: List of users
          schema:
            items:
              $ref: '#/definitions/internal.User'
            type: array
        "400":
          description: Invalid input
        "408":
          description: Request timeout
        "500":
          description: Internal server error
      summary: Get users
      tags:
      - users
  /get_user_tasks:
    get:
      consumes:
      - application/json
      parameters:
      - description: Page number
        in: query
        name: page
        required: true
        type: string
      - description: Number of items per page
        in: query
        name: per_page
        required: true
        type: string
      - description: User ID
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of tasks
          schema:
            items:
              $ref: '#/definitions/internal.Task'
            type: array
        "400":
          description: Invalid input
        "408":
          description: Request timeout
        "500":
          description: Internal server error
      summary: Get user's tasks
      tags:
      - tasks
  /make_task:
    post:
      consumes:
      - application/json
      parameters:
      - description: Task ID
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/internal.Task'
      produces:
      - application/json
      responses:
        "200":
          description: Success
        "400":
          description: Invalid input
        "408":
          description: Request timeout
        "500":
          description: Internal server error
      summary: Create task for user
      tags:
      - tasks
  /stop_task:
    post:
      consumes:
      - application/json
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
        "400":
          description: Invalid input
        "408":
          description: Request timeout
        "500":
          description: Internal server error
      summary: Stop task
      tags:
      - tasks
  /update_user:
    post:
      consumes:
      - application/json
      description: Update user data
      parameters:
      - description: Update details
        in: body
        name: user
        schema:
          $ref: '#/definitions/internal.User'
      produces:
      - application/json
      responses:
        "200":
          description: Success
        "400":
          description: Invalid input
        "408":
          description: Request timeout
        "500":
          description: Internal server error
      summary: Update user
      tags:
      - users
swagger: "2.0"
